name: github action code setup

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main
  #   - 'features/**'
  # pull_request:
  #   branches:
  #   - 'features/**'
  # schedule:
  # - cron: "0 3 * * 1-5"
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform_init_and_plan:
    name: terraform init and plan
    runs-on: [self-hosted, souravrun]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
        continue-on-error: true
    
  terraform_apply:   
    name: apply
    runs-on: souravrun
    needs: terraform_init_and_plan
    environment: dev
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        id: init
        run: terraform init    

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
